changelog:
  exclude:
    labels:
      - ignore-for-release
      - chore
  categories:
    - title: 🚀 New
      labels:
        - enhancement
        - feature
    - title: 🐛 Fix
      labels:
        - bug
        - fix
    - title: 🛠 Other
      labels:
        - '*'
